name: Tests

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.0.0'
          cache: 'npm'

      - name: Run unit tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Run e2e tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          install: false
